create table T_PS_PACIENTE(
    id_paciente number generated by default as identity,
    nome varchar(150),
    telefone varchar(30),
    nascimento date,
    convenio varchar(50),
    primary key(id_paciente)
);